FROM ubuntu:trusty

# build with
#   sudo docker build -f Dockerfile.indigo -t vr-indigo .
# run with
#   sudo docker run -it --name vr-indigo-test -v `pwd`:/ansible:ro vr-indigo

RUN apt-get update
RUN apt-get upgrade --yes

RUN apt-get install --yes ansible

VOLUME /ansible

CMD ansible-playbook -i "localhost," -c local /ansible/playbook-indigo.yml
