- name: install flydra package
  apt: name=python-flydra state=latest

- name: Ensure rosdep sources dir exists
  file: path=/etc/ros/rosdep/sources.list.d state=directory mode=0755 owner=root group=root

- name: Ensure strawlab rosdep URL is included into rosdep sources
  copy: src=40-strawlab-kinetic.list dest=/etc/ros/rosdep/sources.list.d/40-strawlab-kinetic.list owner=root group=root mode=0644

- name: Ensure flydra-kinetic.rosinstall is available
  copy: src=flydra-kinetic.rosinstall dest=/etc/ros/flydra-kinetic.rosinstall owner=root group=root mode=0644

- name: install sudo command
  # This is required by `rosdep install`
  apt: name=sudo state=latest

- name: install wstool command
  # This is required for `wstool`
  apt: name=python-wstool state=latest

- name: install rosinstall command
  apt: name=python-rosinstall state=latest

- name: Ensure workspace installer dir exists
  file: path=/opt/ros/workspace-installers/kinetic/ state=directory mode=0755 owner=root group=root

- name: copy installer script
  copy: src=make-flydra-workspace.sh dest=/opt/ros/workspace-installers/kinetic/make-flydra-workspace.sh owner=root group=root mode=0755

# install missing deps (TODO make ansible find these from ROS packages automatically)
- apt: name=arduino-udev state=latest
- apt: name=libglew-dev state=latest
- apt: name=libsdl1.2-dev state=latest
- apt: name=libcamiface-dev state=latest
- apt: name=python-opencv state=latest
- apt: name=python-blist state=latest
- apt: name=arduino-mk state=latest
- apt: name=gir1.2-gtk-3.0 state=latest
- apt: name=python-gi-cairo state=latest
