- name: get strawlab apt signing key
  apt_key: url=https://strawlab.org/assets/gpg/astraw-{{ ansible_lsb.codename }}.gpg state=present

- name: get strawlab public apt repo
  apt_repository: repo='deb http://debs.strawlab.org/ {{ ansible_lsb.codename }}/'
