- name: Ensure python-apt is installed (prequisite for apt_repository Ansible command)
  # See https://github.com/ansible/ansible/issues/6910
  command: >
    apt-get install python-apt -y -q
    creates=/usr/share/doc/python-apt
  sudo: yes

- name: Ensure python-pycurl is installed (prequisite for apt_repository Ansible command)
  apt: name=python-pycurl state=latest

# These are needed to avoid https://github.com/ansible/ansible/issues/12161
- apt: name=curl state=latest
- command: curl -O https://strawlab.org/assets/astraw-archive-keyring.gpg chdir=/etc/apt/sources.list.d creates=/etc/apt/sources.list.d/astraw-archive-keyring.gpg
- apt_key: id=F8DB323D file=/etc/apt/sources.list.d/astraw-archive-keyring.gpg state=present