name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  focal:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install ansible
      run: sudo apt-get install -y ansible
    - name: Build
      run: sudo ansible-playbook -i "localhost," -c local playbook-focal.yml
